## Programa Ingenias+ Data Science

## Trabajando con Pandas

1) Importa las librerias requeridas: `Pandas` y `NumPy`.  

Una buena practica a la hora de escribir codigo es de comentar siempre que estoy haciendo (usando `#`) en la linea anterior. Por mas obvio que parezca lo que voy a hacer, puede ser que tenga que compartir el documento con otras personas y no sepan que quise hacer en cada linea. O que yo mismo lea el codigo tiempo despues y no recuerde porque lo hice.

In [ ]:
import pandas as pd
import numpy as np

2) Lee el archivo csv `life_expectancy_data` usando `pandas`. Guardalo en una variable llamada `expvida`.

In [ ]:
from google.colab import drive
drive.mount('/content/drive') ## esto lo hice para importar del drive mi archivo

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
from google.colab import files

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
pd.read_csv('/content/drive/MyDrive/DATA SCIENTIST/life_expectancy_data.csv')

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,Zimbabwe,2004,Developing,44.3,723.0,27,4.36,0.000000,68.0,31,...,67.0,7.13,65.0,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2
2934,Zimbabwe,2003,Developing,44.5,715.0,26,4.06,0.000000,7.0,998,...,7.0,6.52,68.0,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5
2935,Zimbabwe,2002,Developing,44.8,73.0,25,4.43,0.000000,73.0,304,...,73.0,6.53,71.0,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0
2936,Zimbabwe,2001,Developing,45.3,686.0,25,1.72,0.000000,76.0,529,...,76.0,6.16,75.0,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8
2937,Zimbabwe,2000,Developing,46.0,665.0,24,1.68,0.000000,79.0,1483,...,78.0,7.10,78.0,43.5,547.358878,12222251.0,11.0,11.2,0.434,9.8

In [ ]:
expvidadf= pd.read_csv('/content/drive/MyDrive/DATA SCIENTIST/life_expectancy_data.csv')  ## ver porque no me salio

In [ ]:
expvidadf.info(())

NameError: ignored

In [ ]:
dataframe = pd.read_csv('/life_expectancy_data.csv') # leo el archivo  que cargue a la carpeta desde afuera del drive

FileNotFoundError: ignored

# Nueva sección

3) ¿Que tipo de estructura de datos contiene la variable `expvida`?

In [ ]:
# Obtengo el nombre de las columnas y el dtype de cada columna
expvidadf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2938 entries, 0 to 2937
Data columns (total 22 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Country                          2938 non-null   object
 1   Year                             2938 non-null   int64
 2   Status                           2938 non-null   object
 3   Life expectancy                  2928 non-null   float64
 4   Adult Mortality                  2928 non-null   float64
 5   infant deaths                    2938 non-null   int64
 6   Alcohol                          2744 non-null   float64
 7   percentage expenditure           2938 non-null   float64
 8   Hepatitis B                      2385 non-null   float64
 9   Measles                          2938 non-null   int64
 10   BMI                             2904 non-null   float64
 11  under-five deaths                2938 non-null   int64
 12  Polio                            2919 non-null   float64
 13  Total expenditure                2712 non-null   float64
 14  Diphtheria                       2919 non-null   float64
 15   HIV/AIDS                        2938 non-null   float64
 16  GDP                              2490 non-null   float64
 17  Population                       2286 non-null   float64
 18   thinness  1-19 years            2904 non-null   float64
 19   thinness 5-9 years              2904 non-null   float64
 20  Income composition of resources  2771 non-null   float64
 21  Schooling                        2775 non-null   float64
dtypes: float64(16), int64(4), object(2)
memory usage: 505.1+ KB

In [ ]:
## es un dataframe con columnas y filas

4) ¿Cuantas filas y columnas tiene `expvida`?

In [ ]:
# Uso .shape para obtener cantidad de filas y columnas
expvidadf.shape

(2938, 22)

2938**Numero de filas**:

22**Numero de columnas**:

5) ¿Cual es el nombre de las columnas contenidas en `expvida`?

In [ ]:
# Obtengo el nombre de las columnas
expvidadf.columns

Index(['Country', 'Year', 'Status', 'Life expectancy ', 'Adult Mortality',
       'infant deaths', 'Alcohol', 'percentage expenditure', 'Hepatitis B',
       'Measles ', ' BMI ', 'under-five deaths ', 'Polio', 'Total expenditure',
       'Diphtheria ', ' HIV/AIDS', 'GDP', 'Population',
       ' thinness  1-19 years', ' thinness 5-9 years',
       'Income composition of resources', 'Schooling'],
      dtype='object')

6) Inspecciona las primeras 10 filas de `expvida`

In [ ]:
expvidadf.head()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

7) Y ahora las 10 ultimas.

In [ ]:
expvidadf.tail(10)

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
2928,Zimbabwe,2009,Developing,50.0,587.0,30,4.64,1.040021,73.0,853,...,69.0,6.26,73.0,18.1,65.824121,1381599.0,7.5,7.4,0.419,9.9
2929,Zimbabwe,2008,Developing,48.2,632.0,30,3.56,20.843429,75.0,0,...,75.0,4.96,75.0,20.5,325.678573,13558469.0,7.8,7.8,0.421,9.7
2930,Zimbabwe,2007,Developing,46.6,67.0,29,3.88,29.814566,72.0,242,...,73.0,4.47,73.0,23.7,396.998217,1332999.0,8.2,8.2,0.414,9.6
2931,Zimbabwe,2006,Developing,45.4,7.0,28,4.57,34.262169,68.0,212,...,71.0,5.12,7.0,26.8,414.796232,13124267.0,8.6,8.6,0.408,9.5
2932,Zimbabwe,2005,Developing,44.6,717.0,28,4.14,8.717409,65.0,420,...,69.0,6.44,68.0,30.3,444.765750,129432.0,9.0,9.0,0.406,9.3
2933,Zimbabwe,2004,Developing,44.3,723.0,27,4.36,0.000000,68.0,31,...,67.0,7.13,65.0,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2
2934,Zimbabwe,2003,Developing,44.5,715.0,26,4.06,0.000000,7.0,998,...,7.0,6.52,68.0,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5
2935,Zimbabwe,2002,Developing,44.8,73.0,25,4.43,0.000000,73.0,304,...,73.0,6.53,71.0,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0
2936,Zimbabwe,2001,Developing,45.3,686.0,25,1.72,0.000000,76.0,529,...,76.0,6.16,75.0,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8
2937,Zimbabwe,2000,Developing,46.0,665.0,24,1.68,0.000000,79.0,1483,...,78.0,7.10,78.0,43.5,547.358878,12222251.0,11.0,11.2,0.434,9.8

8) ¿Que tipos de datos contiene cada una de las columnas de `expvida`?

In [ ]:

# Tipo de datos en cada columna
expvidadf.dtypes

Country                             object
Year                                 int64
Status                              object
Life expectancy                    float64
Adult Mortality                    float64
infant deaths                        int64
Alcohol                            float64
percentage expenditure             float64
Hepatitis B                        float64
Measles                              int64
 BMI                               float64
under-five deaths                    int64
Polio                              float64
Total expenditure                  float64
Diphtheria                         float64
 HIV/AIDS                          float64
GDP                                float64
Population                         float64
 thinness  1-19 years              float64
 thinness 5-9 years                float64
Income composition of resources    float64
Schooling                          float64
dtype: object

In [ ]:
# Inspecciono las ultimas filas
expvidadf.tail()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
2933,Zimbabwe,2004,Developing,44.3,723.0,27,4.36,0.0,68.0,31,...,67.0,7.13,65.0,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2
2934,Zimbabwe,2003,Developing,44.5,715.0,26,4.06,0.0,7.0,998,...,7.0,6.52,68.0,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5
2935,Zimbabwe,2002,Developing,44.8,73.0,25,4.43,0.0,73.0,304,...,73.0,6.53,71.0,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0
2936,Zimbabwe,2001,Developing,45.3,686.0,25,1.72,0.0,76.0,529,...,76.0,6.16,75.0,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8
2937,Zimbabwe,2000,Developing,46.0,665.0,24,1.68,0.0,79.0,1483,...,78.0,7.10,78.0,43.5,547.358878,12222251.0,11.0,11.2,0.434,9.8

9) ¿Hay valores faltantes en alguna de las columnas de `expvida`? si

In [ ]:
# Obtengo la cantidad de datos faltantes en cada columna
expvidadf.isnull

<bound method DataFrame.isnull of           Country  Year      Status  Life expectancy   Adult Mortality  \
0     Afghanistan  2015  Developing              65.0            263.0
1     Afghanistan  2014  Developing              59.9            271.0
2     Afghanistan  2013  Developing              59.9            268.0
3     Afghanistan  2012  Developing              59.5            272.0
4     Afghanistan  2011  Developing              59.2            275.0
...           ...   ...         ...               ...              ...
2933     Zimbabwe  2004  Developing              44.3            723.0
2934     Zimbabwe  2003  Developing              44.5            715.0
2935     Zimbabwe  2002  Developing              44.8             73.0
2936     Zimbabwe  2001  Developing              45.3            686.0
2937     Zimbabwe  2000  Developing              46.0            665.0

      infant deaths  Alcohol  percentage expenditure  Hepatitis B  Measles   \
0                62     0.01               71.279624         65.0      1154
1                64     0.01               73.523582         62.0       492
2                66     0.01               73.219243         64.0       430
3                69     0.01               78.184215         67.0      2787
4                71     0.01                7.097109         68.0      3013
...             ...      ...                     ...          ...       ...
2933             27     4.36                0.000000         68.0        31
2934             26     4.06                0.000000          7.0       998
2935             25     4.43                0.000000         73.0       304
2936             25     1.72                0.000000         76.0       529
2937             24     1.68                0.000000         79.0      1483

      ...  Polio  Total expenditure  Diphtheria    HIV/AIDS         GDP  \
0     ...    6.0               8.16         65.0        0.1  584.259210
1     ...   58.0               8.18         62.0        0.1  612.696514
2     ...   62.0               8.13         64.0        0.1  631.744976
3     ...   67.0               8.52         67.0        0.1  669.959000
4     ...   68.0               7.87         68.0        0.1   63.537231
...   ...    ...                ...          ...        ...         ...
2933  ...   67.0               7.13         65.0       33.6  454.366654
2934  ...    7.0               6.52         68.0       36.7  453.351155
2935  ...   73.0               6.53         71.0       39.8   57.348340
2936  ...   76.0               6.16         75.0       42.1  548.587312
2937  ...   78.0               7.10         78.0       43.5  547.358878

      Population   thinness  1-19 years   thinness 5-9 years  \
0     33736494.0                   17.2                 17.3
1       327582.0                   17.5                 17.5
2     31731688.0                   17.7                 17.7
3      3696958.0                   17.9                 18.0
4      2978599.0                   18.2                 18.2
...          ...                    ...                  ...
2933  12777511.0                    9.4                  9.4
2934  12633897.0                    9.8                  9.9
2935    125525.0                    1.2                  1.3
2936  12366165.0                    1.6                  1.7
2937  12222251.0                   11.0                 11.2

      Income composition of resources  Schooling
0                               0.479       10.1
1                               0.476       10.0
2                               0.470        9.9
3                               0.463        9.8
4                               0.454        9.5
...                               ...        ...
2933                            0.407        9.2
2934                            0.418        9.5
2935                            0.427       10.0
2936                            0.427        9.8
2937                            0.434        9.8

[2938 rows x 22 columns]>

10) Selecciona el maximo de datos faltantes. Calcula que porcentaje de los datos representan los datos faltantes.

In [ ]:
# Obtengo la cantidad de filas total y divido el maximo valor de datos faltantes por este numero
# y lo multiplico por 100 ---Verificar .,... no me salio
expvidadf.sum

<bound method NDFrame._add_numeric_operations.<locals>.sum of           Country  Year      Status  Life expectancy   Adult Mortality  \
0     Afghanistan  2015  Developing              65.0            263.0
1     Afghanistan  2014  Developing              59.9            271.0
2     Afghanistan  2013  Developing              59.9            268.0
3     Afghanistan  2012  Developing              59.5            272.0
4     Afghanistan  2011  Developing              59.2            275.0
...           ...   ...         ...               ...              ...
2933     Zimbabwe  2004  Developing              44.3            723.0
2934     Zimbabwe  2003  Developing              44.5            715.0
2935     Zimbabwe  2002  Developing              44.8             73.0
2936     Zimbabwe  2001  Developing              45.3            686.0
2937     Zimbabwe  2000  Developing              46.0            665.0

      infant deaths  Alcohol  percentage expenditure  Hepatitis B  Measles   \
0                62     0.01               71.279624         65.0      1154
1                64     0.01               73.523582         62.0       492
2                66     0.01               73.219243         64.0       430
3                69     0.01               78.184215         67.0      2787
4                71     0.01                7.097109         68.0      3013
...             ...      ...                     ...          ...       ...
2933             27     4.36                0.000000         68.0        31
2934             26     4.06                0.000000          7.0       998
2935             25     4.43                0.000000         73.0       304
2936             25     1.72                0.000000         76.0       529
2937             24     1.68                0.000000         79.0      1483

      ...  Polio  Total expenditure  Diphtheria    HIV/AIDS         GDP  \
0     ...    6.0               8.16         65.0        0.1  584.259210
1     ...   58.0               8.18         62.0        0.1  612.696514
2     ...   62.0               8.13         64.0        0.1  631.744976
3     ...   67.0               8.52         67.0        0.1  669.959000
4     ...   68.0               7.87         68.0        0.1   63.537231
...   ...    ...                ...          ...        ...         ...
2933  ...   67.0               7.13         65.0       33.6  454.366654
2934  ...    7.0               6.52         68.0       36.7  453.351155
2935  ...   73.0               6.53         71.0       39.8   57.348340
2936  ...   76.0               6.16         75.0       42.1  548.587312
2937  ...   78.0               7.10         78.0       43.5  547.358878

      Population   thinness  1-19 years   thinness 5-9 years  \
0     33736494.0                   17.2                 17.3
1       327582.0                   17.5                 17.5
2     31731688.0                   17.7                 17.7
3      3696958.0                   17.9                 18.0
4      2978599.0                   18.2                 18.2
...          ...                    ...                  ...
2933  12777511.0                    9.4                  9.4
2934  12633897.0                    9.8                  9.9
2935    125525.0                    1.2                  1.3
2936  12366165.0                    1.6                  1.7
2937  12222251.0                   11.0                 11.2

      Income composition of resources  Schooling
0                               0.479       10.1
1                               0.476       10.0
2                               0.470        9.9
3                               0.463        9.8
4                               0.454        9.5
...                               ...        ...
2933                            0.407        9.2
2934                            0.418        9.5
2935                            0.427       10.0
2936                            0.427        9.8
2937                            0.434        9.8

[2938 rows x 22 columns]>

In [ ]:
# Obtengo el maximo valor de datos faltantes y lo guardo en la variable masnan
expvidadf.max

<bound method NDFrame._add_numeric_operations.<locals>.max of           Country  Year      Status  Life expectancy   Adult Mortality  \
0     Afghanistan  2015  Developing              65.0            263.0
1     Afghanistan  2014  Developing              59.9            271.0
2     Afghanistan  2013  Developing              59.9            268.0
3     Afghanistan  2012  Developing              59.5            272.0
4     Afghanistan  2011  Developing              59.2            275.0
...           ...   ...         ...               ...              ...
2933     Zimbabwe  2004  Developing              44.3            723.0
2934     Zimbabwe  2003  Developing              44.5            715.0
2935     Zimbabwe  2002  Developing              44.8             73.0
2936     Zimbabwe  2001  Developing              45.3            686.0
2937     Zimbabwe  2000  Developing              46.0            665.0

      infant deaths  Alcohol  percentage expenditure  Hepatitis B  Measles   \
0                62     0.01               71.279624         65.0      1154
1                64     0.01               73.523582         62.0       492
2                66     0.01               73.219243         64.0       430
3                69     0.01               78.184215         67.0      2787
4                71     0.01                7.097109         68.0      3013
...             ...      ...                     ...          ...       ...
2933             27     4.36                0.000000         68.0        31
2934             26     4.06                0.000000          7.0       998
2935             25     4.43                0.000000         73.0       304
2936             25     1.72                0.000000         76.0       529
2937             24     1.68                0.000000         79.0      1483

      ...  Polio  Total expenditure  Diphtheria    HIV/AIDS         GDP  \
0     ...    6.0               8.16         65.0        0.1  584.259210
1     ...   58.0               8.18         62.0        0.1  612.696514
2     ...   62.0               8.13         64.0        0.1  631.744976
3     ...   67.0               8.52         67.0        0.1  669.959000
4     ...   68.0               7.87         68.0        0.1   63.537231
...   ...    ...                ...          ...        ...         ...
2933  ...   67.0               7.13         65.0       33.6  454.366654
2934  ...    7.0               6.52         68.0       36.7  453.351155
2935  ...   73.0               6.53         71.0       39.8   57.348340
2936  ...   76.0               6.16         75.0       42.1  548.587312
2937  ...   78.0               7.10         78.0       43.5  547.358878

      Population   thinness  1-19 years   thinness 5-9 years  \
0     33736494.0                   17.2                 17.3
1       327582.0                   17.5                 17.5
2     31731688.0                   17.7                 17.7
3      3696958.0                   17.9                 18.0
4      2978599.0                   18.2                 18.2
...          ...                    ...                  ...
2933  12777511.0                    9.4                  9.4
2934  12633897.0                    9.8                  9.9
2935    125525.0                    1.2                  1.3
2936  12366165.0                    1.6                  1.7
2937  12222251.0                   11.0                 11.2

      Income composition of resources  Schooling
0                               0.479       10.1
1                               0.476       10.0
2                               0.470        9.9
3                               0.463        9.8
4                               0.454        9.5
...                               ...        ...
2933                            0.407        9.2
2934                            0.418        9.5
2935                            0.427       10.0
2936                            0.427        9.8
2937                            0.434        9.8

[2938 rows x 22 columns]>

In [ ]:
masman=expvidadf.max

In [ ]:
# Imprimo el maximo porcentaje de datos faltantes. Uso f-strings.
print(f'El maximo porcentaje de datos faltantes es: ')

El maximo porcentaje de datos faltantes es:

- str.format()
- Template Class
- f-strings

#### Ahora vamos a realizar algunos calculos y manipulaciones sobre las columnas.

Una función útil para este fin es: `.rename()`. Y podemos utilizarla de la siguiente manera: Si `df` es mi DataFrame y quiero renombrar la columna `columna` como `columna1`, y la columna `columna2` como `columna3`, utilizo la siguiente sintaxis:
  
`df.rename(columns={"columna": "columna1", "columna2": "columna3"}, inplace=True)`

11) Renombra la columna 'Life expectancy ' como 'life_expectancy', ' BMI ' como 'bmi' y ''Measles ' como 'measles'. No olvides de usar `inplace` para modificar el DataFrame original. Luego chequea que el cambio se haya hecho correctamente.

In [ ]:
# Renombro columnas del DataFrame
expvidadf.columns

Index(['Country', 'Year', 'Status', 'Life expectancy ', 'Adult Mortality',
       'infant deaths', 'Alcohol', 'percentage expenditure', 'Hepatitis B',
       'Measles ', ' BMI ', 'under-five deaths ', 'Polio', 'Total expenditure',
       'Diphtheria ', ' HIV/AIDS', 'GDP', 'Population',
       ' thinness  1-19 years', ' thinness 5-9 years',
       'Income composition of resources', 'Schooling'],
      dtype='object')

In [ ]:
expida2 = expvidadf.rename(columns={'Life expectancy':'life expectancy','BMI':'bmi','Measles':'measles'})

In [ ]:
# Chequeo que se hayan reemplazado correctamente***ver porque no me salio

In [ ]:
expida2.columns

Index(['Country', 'Year', 'Status', 'Life expectancy ', 'Adult Mortality',
       'infant deaths', 'Alcohol', 'percentage expenditure', 'Hepatitis B',
       'Measles ', ' BMI ', 'under-five deaths ', 'Polio', 'Total expenditure',
       'Diphtheria ', ' HIV/AIDS', 'GDP', 'Population',
       ' thinness  1-19 years', ' thinness 5-9 years',
       'Income composition of resources', 'Schooling'],
      dtype='object')

12) ¿Cual es el promedio de expectativa de vida (Life expectancy) en general?

In [ ]:
# Obtengo el promedio de la columna
expvidadf.mean,'Life expectancy'

(<bound method NDFrame._add_numeric_operations.<locals>.mean of           Country  Year      Status  Life expectancy   Adult Mortality  \
 0     Afghanistan  2015  Developing              65.0            263.0
 1     Afghanistan  2014  Developing              59.9            271.0
 2     Afghanistan  2013  Developing              59.9            268.0
 3     Afghanistan  2012  Developing              59.5            272.0
 4     Afghanistan  2011  Developing              59.2            275.0
 ...           ...   ...         ...               ...              ...
 2933     Zimbabwe  2004  Developing              44.3            723.0
 2934     Zimbabwe  2003  Developing              44.5            715.0
 2935     Zimbabwe  2002  Developing              44.8             73.0
 2936     Zimbabwe  2001  Developing              45.3            686.0
 2937     Zimbabwe  2000  Developing              46.0            665.0

       infant deaths  Alcohol  percentage expenditure  Hepatitis B  Measles   \
 0                62     0.01               71.279624         65.0      1154
 1                64     0.01               73.523582         62.0       492
 2                66     0.01               73.219243         64.0       430
 3                69     0.01               78.184215         67.0      2787
 4                71     0.01                7.097109         68.0      3013
 ...             ...      ...                     ...          ...       ...
 2933             27     4.36                0.000000         68.0        31
 2934             26     4.06                0.000000          7.0       998
 2935             25     4.43                0.000000         73.0       304
 2936             25     1.72                0.000000         76.0       529
 2937             24     1.68                0.000000         79.0      1483

       ...  Polio  Total expenditure  Diphtheria    HIV/AIDS         GDP  \
 0     ...    6.0               8.16         65.0        0.1  584.259210
 1     ...   58.0               8.18         62.0        0.1  612.696514
 2     ...   62.0               8.13         64.0        0.1  631.744976
 3     ...   67.0               8.52         67.0        0.1  669.959000
 4     ...   68.0               7.87         68.0        0.1   63.537231
 ...   ...    ...                ...          ...        ...         ...
 2933  ...   67.0               7.13         65.0       33.6  454.366654
 2934  ...    7.0               6.52         68.0       36.7  453.351155
 2935  ...   73.0               6.53         71.0       39.8   57.348340
 2936  ...   76.0               6.16         75.0       42.1  548.587312
 2937  ...   78.0               7.10         78.0       43.5  547.358878

       Population   thinness  1-19 years   thinness 5-9 years  \
 0     33736494.0                   17.2                 17.3
 1       327582.0                   17.5                 17.5
 2     31731688.0                   17.7                 17.7
 3      3696958.0                   17.9                 18.0
 4      2978599.0                   18.2                 18.2
 ...          ...                    ...                  ...
 2933  12777511.0                    9.4                  9.4
 2934  12633897.0                    9.8                  9.9
 2935    125525.0                    1.2                  1.3
 2936  12366165.0                    1.6                  1.7
 2937  12222251.0                   11.0                 11.2

       Income composition of resources  Schooling
 0                               0.479       10.1
 1                               0.476       10.0
 2                               0.470        9.9
 3                               0.463        9.8
 4                               0.454        9.5
 ...                               ...        ...
 2933                            0.407        9.2
 2934                            0.418        9.5
 2935                            0.427       10.0
 2936                            0.427        9.8
 2937                            0.434        9.8

 [2938 rows x 22 columns]>,
 'Life expectancy')

13) ¿Cual es el promedio de expectativa de vida (Life expectancy) por país?

In [ ]:
# Obtengo el promedio por pais

In [ ]:

expvidadf.mean,'Country'

(<bound method NDFrame._add_numeric_operations.<locals>.mean of           Country  Year      Status  Life expectancy   Adult Mortality  \
 0     Afghanistan  2015  Developing              65.0            263.0
 1     Afghanistan  2014  Developing              59.9            271.0
 2     Afghanistan  2013  Developing              59.9            268.0
 3     Afghanistan  2012  Developing              59.5            272.0
 4     Afghanistan  2011  Developing              59.2            275.0
 ...           ...   ...         ...               ...              ...
 2933     Zimbabwe  2004  Developing              44.3            723.0
 2934     Zimbabwe  2003  Developing              44.5            715.0
 2935     Zimbabwe  2002  Developing              44.8             73.0
 2936     Zimbabwe  2001  Developing              45.3            686.0
 2937     Zimbabwe  2000  Developing              46.0            665.0

       infant deaths  Alcohol  percentage expenditure  Hepatitis B  Measles   \
 0                62     0.01               71.279624         65.0      1154
 1                64     0.01               73.523582         62.0       492
 2                66     0.01               73.219243         64.0       430
 3                69     0.01               78.184215         67.0      2787
 4                71     0.01                7.097109         68.0      3013
 ...             ...      ...                     ...          ...       ...
 2933             27     4.36                0.000000         68.0        31
 2934             26     4.06                0.000000          7.0       998
 2935             25     4.43                0.000000         73.0       304
 2936             25     1.72                0.000000         76.0       529
 2937             24     1.68                0.000000         79.0      1483

       ...  Polio  Total expenditure  Diphtheria    HIV/AIDS         GDP  \
 0     ...    6.0               8.16         65.0        0.1  584.259210
 1     ...   58.0               8.18         62.0        0.1  612.696514
 2     ...   62.0               8.13         64.0        0.1  631.744976
 3     ...   67.0               8.52         67.0        0.1  669.959000
 4     ...   68.0               7.87         68.0        0.1   63.537231
 ...   ...    ...                ...          ...        ...         ...
 2933  ...   67.0               7.13         65.0       33.6  454.366654
 2934  ...    7.0               6.52         68.0       36.7  453.351155
 2935  ...   73.0               6.53         71.0       39.8   57.348340
 2936  ...   76.0               6.16         75.0       42.1  548.587312
 2937  ...   78.0               7.10         78.0       43.5  547.358878

       Population   thinness  1-19 years   thinness 5-9 years  \
 0     33736494.0                   17.2                 17.3
 1       327582.0                   17.5                 17.5
 2     31731688.0                   17.7                 17.7
 3      3696958.0                   17.9                 18.0
 4      2978599.0                   18.2                 18.2
 ...          ...                    ...                  ...
 2933  12777511.0                    9.4                  9.4
 2934  12633897.0                    9.8                  9.9
 2935    125525.0                    1.2                  1.3
 2936  12366165.0                    1.6                  1.7
 2937  12222251.0                   11.0                 11.2

       Income composition of resources  Schooling
 0                               0.479       10.1
 1                               0.476       10.0
 2                               0.470        9.9
 3                               0.463        9.8
 4                               0.454        9.5
 ...                               ...        ...
 2933                            0.407        9.2
 2934                            0.418        9.5
 2935                            0.427       10.0
 2936                            0.427        9.8
 2937                            0.434        9.8

 [2938 rows x 22 columns]>,
 'Country')

14) ¿Cual es la expectativa de vida mas alta y mas baja? Usa la funcion de pandas y la funcion de NumPy y compara el resultado. ¿Que paises tienen esas expectativas de vida?

In [ ]:
# Maxima expectativa de vida usando numpy
expvidadf.iloc()

In [ ]:
# Maxima expectativa de vida usando pandas

In [ ]:
# Minima expectativa de vida usando numpy

In [ ]:
# Minima expectativa de vida usando pandas

In [ ]:
# Muestro los resultados maximos

In [ ]:
# Muestro los resultados minimos

In [ ]:
# Filtro las columnas para mostrar solo las filas que tengan valor
# igual al maximo

In [ ]:
# Filtro las columnas para mostrar solo las filas que tengan valor
# igual al minimo

15) ¿Cuantas categorias encontramos en la columna "Status"? _**Pista**_: Lee acerca de la función [unique()](http://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.unique.html?highlight=unique#pandas.Series.unique)

In [ ]:
# Obtengo los valores unicos de la columna status

16) ¿Cuantos paises se ubican en cada una de esas categorias de "Status"? _**Pista**_: Lee acerca de la función [value_counts()](http://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.value_counts.html)

In [ ]:
# Cuento cuantos valores hay de cada categoria

18) ¿Cuantos paises presentaron algun caso de Sarampion (**Measles**) en el 2015? **_Pista_**: Lee acerca de la función [.count()](http://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.count.html?highlight=count#pandas.DataFrame.count)

In [ ]:
# Cuento cuantas filas tienen valores distintos de cero